apiVersion: v1
kind: Pod

metadata:
  name: tools-pod
  labels:
    app: tools
    environment: dev
    team: platform

spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
    - sh
    - -c
    - sleep 3600